<a href="https://colab.research.google.com/github/Aditi-dev07/Pandas_Library/blob/Lib/11_Grouping_for_Insights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import data from kaggle

In [ ]:
import pandas as pd
dd = pd.read_csv("Sales_December_2019.csv")
df = pd.read_csv("Sales_February_2019.csv")
dd.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,295665,Macbook Pro Laptop,1,1700,12/30/19 00:01,"136 Church St, New York City, NY 10001"
1,295666,LG Washing Machine,1,600.0,12/29/19 07:03,"562 2nd St, New York City, NY 10001"
2,295667,USB-C Charging Cable,1,11.95,12/12/19 18:21,"277 Main St, New York City, NY 10001"
3,295668,27in FHD Monitor,1,149.99,12/22/19 15:13,"410 6th St, San Francisco, CA 94016"
4,295669,USB-C Charging Cable,1,11.95,12/18/19 12:38,"43 Hill St, Atlanta, GA 30301"

### Process and Aggregate Sales Data

In [ ]:
all_data = pd.concat([dd, df], ignore_index=True)

# Convert 'Order Date' to datetime objects
all_data['Order Date'] = pd.to_datetime(all_data['Order Date'], errors='coerce')

# Drop rows with NaN values that resulted from coercion
all_data.dropna(subset=['Order Date', 'Quantity Ordered', 'Price Each'], inplace=True)

# Convert 'Quantity Ordered' and 'Price Each' to numeric types
all_data['Quantity Ordered'] = pd.to_numeric(all_data['Quantity Ordered'])
all_data['Price Each'] = pd.to_numeric(all_data['Price Each'])

# Extract month and year
all_data['Month'] = all_data['Order Date'].dt.month
all_data['Year'] = all_data['Order Date'].dt.year

/tmp/ipython-input-845125639.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  all_data['Order Date'] = pd.to_datetime(all_data['Order Date'], errors='coerce')

### Multi-level Grouping and Aggregation with `groupby()` and `.agg()`

In [ ]:
# Multi-level grouping and aggregation
monthly_sales = all_data.groupby(['Year', 'Month']).agg(
    Total_Quantity=('Quantity Ordered', 'sum'),
    Total_Sales=('Price Each', lambda x: (x * all_data.loc[x.index, 'Quantity Ordered']).sum()),
    Number_of_Orders=('Order ID', 'count')
).reset_index()

display(monthly_sales)

   Year  Month  Total_Quantity  Total_Sales  Number_of_Orders
0  2019      2           13443   2200273.74             11969
1  2019      3              18      3207.50                17
2  2019     12           13549   2210486.45             12003
3  2020      1              22      5759.55                18