<a href="https://colab.research.google.com/github/Aditi-dev07/Pandas_Library/blob/Lib/13_Reshaping_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sales Data Analysis

This notebook analyzes sales data to understand sales performance by region and product category.

## Load Data
https://realpython.com/bonus/how-to-pandas-pivot-table-code/

This cell loads the sales data from the `sales_data.csv` file into a pandas DataFrame and displays the first 5 rows to preview the data structure.

In [6]:
import pandas as pd
df = pd.read_csv("sales_data.csv")
df.head(5)

,order_number,employee_id,employee_name,job_title,sales_region,order_date,order_type,customer_type,customer_name,customer_state,product_category,product_number,produce_name,quantity,unit_price,sale_price
0,1102935,900019019,Alexandra Kundt,Senior Sales Associate,S Central East,09/02/2019,Retail,Individual,Skipton Fealty,Arkansas,Olive Oil,OO206,Chili Extra Virgin Olive Oil 2pk,3,45.0,135.0
1,1102976,900019019,Alexandra Kundt,Senior Sales Associate,S Central East,15/02/2019,Retail,Individual,Lanni D'Ambrogi,Missouri,Gift Basket,GB301,Scented Olive Oil Candle Gift Basket,1,19.5,19.5
2,1102988,900019019,Alexandra Kundt,Senior Sales Associate,S Central East,16/02/2019,Retail,Individual,Far Pow,Mississippi,Olive Oil,OO302,Chili Extra Virgin Olive Oil,4,26.0,104.0
3,1103012,900019019,Alexandra Kundt,Senior Sales Associate,S Central East,19/02/2019,Wholesale,Business,Swift Inc,Texas,Olive Oil,OO125,Garlic Extra Virgin Olive Oil 12pk,4,234.0,936.0
4,1103031,900019019,Alexandra Kundt,Senior Sales Associate,S Central East,22/02/2019,Retail,Individual,Carmine Priestnall,Texas,Olive Oil,OO128,Chili Extra Virgin Olive Oil 12pk,3,234.0,702.0

## Generate Pivot Table

This cell creates a pivot table from the DataFrame to show the total `sale_price` for each `sales_region` and `product_category`. The `aggfunc='sum'` argument calculates the sum of `sale_price` for each group

In [7]:
pivot_table = df.pivot_table(values='sale_price', index='sales_region', columns='product_category', aggfunc='sum')
display(pivot_table)

product_category  Bath products  Gift Basket  Olive Oil
sales_region
Central East            5315.40      16309.5  230126.50
N Central East          6905.36      21533.0  241459.75
N Central West           690.92       2023.5    9023.50
Northeast               4267.56      16985.0  190249.75
Northwest               1909.24       6115.0   59781.50
S Central East          7458.55      25524.5  306705.00
S Central West          2250.08       9118.0   94364.75
Southeast               5101.97      18900.5  199862.25
Southwest               5897.97      19232.0  201590.75

## Calculate Total Sales by Product Category

This cell calculates the total sales for each product category by grouping the DataFrame by `product_category` and summing the `sale_price`.

In [10]:
total_sales_by_category = df.groupby('product_category')['sale_price'].sum()
display(total_sales_by_category)

product_category
Bath products      39797.05
Gift Basket       135741.00
Olive Oil        1533163.75
Name: sale_price, dtype: float64