<a href="https://colab.research.google.com/github/Aditi-dev07/Pandas_Library/blob/Lib/5_Sorting_and_Ranking_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Load the Dataset

In [ ]:
import pandas as pd
df= pd.read_csv("Datafiniti_Womens_Shoes.csv")
df.head()

#sort_values() is a function in the pandas library that allows you to sort a DataFrame by the values in one or more columns. You can specify whether to sort in ascending or descending order

In [ ]:
df_sorted = df.sort_values(by='dateUpdated', ascending=False)
display(df_sorted.head())

,id,dateAdded,dateUpdated,asins,brand,categories,primaryCategories,colors,dimension,ean,...,prices.merchant,prices.offer,prices.returnPolicy,prices.shipping,prices.size,prices.sourceURLs,sizes,sourceURLs,upc,weight
5,AVpg91ziilAPnD_xziOo,2017-01-09T19:38:58Z,2018-10-23T21:26:11Z,NaN,Soft Ones,"Womens Shoes,Clothing,Women's Shoes,Baby & Kid...",Shoes,Brown Tweed,4.0 in x 3.5 in x 9.0 in,3.397705e+10,...,Walmart.com,NaN,NaN,Expedited,5,https://www.walmart.com/ip/MUK-LUKS-Sock-Monke...,"5,6.5,9,11",https://www.walmart.com/ip/Soft-Ones-Kid-s-Soc...,033977052222,NaN
6,AVpjGKXyLJeJML43r8BH,2017-01-17T19:09:21Z,2018-10-15T15:50:13Z,NaN,MUK LUKS,"MUK LUKS,Womens,Women's Casual Shoes,Clothing,...",Shoes,"Light Blue,Brown,Navy,Purple,Burgundy,Black,Na...",NaN,3.397717e+10,...,NaN,NaN,NaN,NaN,SMALL,https://www.kohls.com/product/prd-1780800/wome...,"S 5-6,SMALL,M 7-8,MEDIUM,LARGE,L 9-10,L 8-9",https://www.walmart.com/ip/Women-s-Clog-with-F...,033977098275,NaN
7,AVpjGKXyLJeJML43r8BH,2017-01-17T19:09:21Z,2018-10-15T15:50:13Z,NaN,MUK LUKS,"MUK LUKS,Womens,Women's Casual Shoes,Clothing,...",Shoes,"Light Blue,Brown,Navy,Purple,Burgundy,Black,Na...",NaN,3.397717e+10,...,NaN,NaN,NaN,NaN,MEDIUM,https://www.kohls.com/product/prd-1780800/wome...,"S 5-6,SMALL,M 7-8,MEDIUM,LARGE,L 9-10,L 8-9",https://www.walmart.com/ip/Women-s-Clog-with-F...,033977098275,NaN
21,AVpfGWT3ilAPnD_xU7MQ,2016-04-28T18:44:11Z,2018-06-05T22:29:16Z,NaN,Sloggers,"Womens Shoes,Clothing,Women's Shoes,All Womens...",Shoes,"N/a,Kiwi,Blue,Black",6.5 in x 8.5 in x 12.5 in,9.105301e+10,...,Walmart.com,NaN,NaN,Standard,6,https://www.walmart.com/ip/Sloggers-Women-s-Ou...,"10,7,6,9,8",http://www.walmart.com/ip/Sloggers-Women-s-Gar...,091053008129,NaN
132,AVpfWLtyilAPnD_xaGle,2017-01-24T18:09:32Z,2018-06-05T22:28:50Z,NaN,Unbranded,"Women's Casual Shoes,Womens Casual Shoes,Women...",Shoes,Black,6.00 in x 6.00 in x 1.00 in,6.053880e+11,...,Walmart.com,NaN,NaN,NaN,6,https://www.walmart.com/ip/Women-s-Basic-Balle...,"8.5,10,7,6,9.5,6.5,7.5,9,8,11",https://www.walmart.com/ip/Women-s-Basic-Balle...,605388000000,NaN

In [ ]:
# Sort by a single column in ascending order
df_sorted_asc = df.sort_values(by='dateAdded', ascending=False)
print("Sorting by 'dateAdded' in ascending order:")
display(df_sorted_asc.head())

# Sort by multiple columns
# Sort by 'brand' in ascending order and then by 'dateAdded' in descending order
df_sorted_multi = df.sort_values(by=['brand', 'dateAdded'], ascending=[False , False])
print("\nSorting by 'brand' (ascending) and 'dateAdded' (descending):")
display(df_sorted_multi.head())

Sorting by 'dateAdded' in ascending order:

,id,dateAdded,dateUpdated,asins,brand,categories,primaryCategories,colors,dimension,ean,...,prices.merchant,prices.offer,prices.returnPolicy,prices.shipping,prices.size,prices.sourceURLs,sizes,sourceURLs,upc,weight
205,AWEWhqysYSSHbkXwu0Bm,2018-01-21T02:17:39Z,2018-01-21T02:17:39Z,NaN,easy street,"Womens,Shoes,Oxfords,Easy Street",Shoes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9.5 MED,https://www.kohls.com/product/prd-2613222/easy...,9.5 MED,https://www.kohls.com/product/prd-2613222/easy...,886066000000,NaN
150,AWENYGmcHh53nbDREgGO,2018-01-19T07:40:46Z,2018-01-21T05:28:40Z,NaN,naturalsoul by naturalizer,"Womens,Shoes,Sandals,NaturalSoul by naturalizer",Shoes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9 MED,https://www.kohls.com/product/prd-2922415/natu...,9 MED,https://www.kohls.com/product/prd-2922415/natu...,727685000000,NaN
130,AWDXWRLjuC1rwyj_lXHA,2018-01-08T19:03:08Z,2018-01-09T05:50:13Z,NaN,lc lauren conrad,"Womens,Shoes,Boots,LC Lauren Conrad",Shoes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9,https://www.kohls.com/product/prd-2692507/lc-l...,9,https://www.kohls.com/product/prd-2692507/lc-l...,400767000000,NaN
161,AWDG0cpmHh53nbDREARo,2018-01-05T14:54:25Z,2018-01-19T08:31:54Z,NaN,corkys,"Womens,Shoes,Pumps,Heels,Corkys",Shoes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,11,https://www.kohls.com/product/prd-2571729/cork...,11,https://www.kohls.com/product/prd-2571729/cork...,802616000000,NaN
149,AWDG0nOkuC1rwyj_lPOj,2018-01-05T14:54:15Z,2018-01-09T21:18:20Z,NaN,lifestride,"Womens,Shoes,Boots,LifeStride","Shoes,Shoes",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5 MED,https://www.kohls.com/product/prd-2661199/life...,5 MED,https://www.kohls.com/product/prd-2661199/life...,727680000000,NaN

Sorting by 'brand' (ascending) and 'dateAdded' (descending):

,id,dateAdded,dateUpdated,asins,brand,categories,primaryCategories,colors,dimension,ean,...,prices.merchant,prices.offer,prices.returnPolicy,prices.shipping,prices.size,prices.sourceURLs,sizes,sourceURLs,upc,weight
612,AV-nbamiYSSHbkXwpZrw,2017-11-10T19:32:52Z,2018-02-01T07:34:57Z,NaN,under armour,"Womens,Shoes,Athletic Shoes,Sneakers,Under Armour",Shoes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.5,https://www.kohls.com/product/prd-2932795/unde...,"5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10,11,12",https://www.kohls.com/product/prd-2932795/unde...,"190078356274,190078356281,190510812986,1900783...",NaN
613,AV-nbamiYSSHbkXwpZrw,2017-11-10T19:32:52Z,2018-02-01T07:34:57Z,NaN,under armour,"Womens,Shoes,Athletic Shoes,Sneakers,Under Armour",Shoes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.5,https://www.kohls.com/product/prd-2932795/unde...,"5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10,11,12",https://www.kohls.com/product/prd-2932795/unde...,"190078356274,190078356281,190510812986,1900783...",NaN
604,AV-nbamiYSSHbkXwpZrw,2017-11-10T19:32:52Z,2018-02-01T07:34:57Z,NaN,under armour,"Womens,Shoes,Athletic Shoes,Sneakers,Under Armour",Shoes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7,https://www.kohls.com/product/prd-2932795/unde...,"5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10,11,12",https://www.kohls.com/product/prd-2932795/unde...,"190078356274,190078356281,190510812986,1900783...",NaN
605,AV-nbamiYSSHbkXwpZrw,2017-11-10T19:32:52Z,2018-02-01T07:34:57Z,NaN,under armour,"Womens,Shoes,Athletic Shoes,Sneakers,Under Armour",Shoes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12,https://www.kohls.com/product/prd-2932795/unde...,"5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10,11,12",https://www.kohls.com/product/prd-2932795/unde...,"190078356274,190078356281,190510812986,1900783...",NaN
606,AV-nbamiYSSHbkXwpZrw,2017-11-10T19:32:52Z,2018-02-01T07:34:57Z,NaN,under armour,"Womens,Shoes,Athletic Shoes,Sneakers,Under Armour",Shoes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6.5,https://www.kohls.com/product/prd-2932795/unde...,"5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10,11,12",https://www.kohls.com/product/prd-2932795/unde...,"190078356274,190078356281,190510812986,1900783...",NaN