<a href="https://colab.research.google.com/github/Aditi-dev07/Pandas_Library/blob/Lib/6_Basic_Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import dataset from kaggel
https://www.kaggle.com/datasets/mosapabdelghany/medical-insurance-cost-dataset

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mosapabdelghany/medical-insurance-cost-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'medical-insurance-cost-dataset' dataset.
Path to dataset files: /kaggle/input/medical-insurance-cost-dataset

In [ ]:
import pandas as pd
df = pd.read_csv(path + '/insurance.csv')
display(df.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

#Functions
.describe(), .mean(), .median(), .value_counts()

In [ ]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

.Median() Function

In [ ]:
df['charges'].median()

9382.033

.Mean() Function

In [ ]:
df["age"].mean()

np.float64(39.20702541106129)

.value_counts() Function

In [ ]:
smoker_s = df.value_counts("smoker")
print(smoker_s)

smoker
no     1064
yes     274
Name: count, dtype: int64