<a href="https://colab.research.google.com/github/Aditi-dev07/Pandas_Library/blob/Lib/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####**Data Cleaning - Handling Missing Values**


**Import Dataset from Kaggel**

 https://www.kaggle.com/c/titanic/data?select=test.csv


**Import Pandas as pd**

In [ ]:
import pandas as pd

####**Load the Dataset with pd.read_csv("") Function**

In [ ]:
df = pd.read_csv("Titanic.csv")

####**df.isnull to know the empty values**

In [ ]:
df.isnull()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
413,False,False,False,False,True,False,False,False,False,True,False
414,False,False,False,False,False,False,False,False,False,False,False
415,False,False,False,False,False,False,False,False,False,True,False
416,False,False,False,False,True,False,False,False,False,True,False
417,False,False,False,False,True,False,False,False,False,True,False

** **

####**df.sum() Function to calculate total number of empty values based on columns**

In [ ]:
df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

####**df.dropna() for drop missing values**

In [ ]:
df = df.dropna('Cabin', axis=1 , inplace=True)

####**df.fillna() to fill missing values by medain**

In [36]:
median_age = df['Age'].median()
df['Age'].fillna(median_age, inplace=True)

median_fare = df['Fare'].median()
df['Fare'].fillna(median_fare, inplace=True)

print("Missing values after filling:")
print(df.isnull().sum())

Missing values after filling:
PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

/tmp/ipython-input-1937424637.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(median_age, inplace=True)
/tmp/ipython-input-1937424637.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fare'].fillna(median_fare, inplace=True)